Feature/posts reactions
juancoelhoo/pet-adoption pull request #17
Opened 2024-06-16 21:55 UTC by beviggiano

This PR introduces the implementation of reaction creation for posts within the application. The main objective is to enable users to react to posts, specifically through likes. This includes the necessary model, repository, controller, and route configurations.

2024-06-16 23:47 UTC, edu-correia requested changes
Just one point to fix

2024-06-16 23:47 UTC, edu-correia commented on backend/src/infra/api/modules/reactions/controller.ts
> +class ReactionsController {
Missing docs comments for this controller

2024-06-18 02:24 UTC, edu-correia requested changes
Looks good to me, lets just use the config file for the api on frontend

2024-06-18 02:24 UTC, edu-correia commented on frontend/src/components/PetAd/PetAd.tsx
> +    axios.get('http://localhost:3333/reactions')
use:
```ts
import api from "src/services/api.ts";
...
api.get("/reactions");
```
instead of using axios directly.

This api file is a config file, used to change backend url in the entire project.

2024-06-18 02:24 UTC, edu-correia commented on frontend/src/components/PetAd/PetAd.tsx
> +      const response = await axios.post('http://localhost:3333/reactions/toggleLike', {
same here

2024-06-19 12:26 UTC, juancoelhoo approved these changes

2024-06-22 17:41 UTC, edu-correia approved these changes
LGTM

2024-06-22 17:44 UTC, merged