Implement Complaints Functionality and Popup Reporting Feature
juancoelhoo/pet-adoption pull request #18
Opened 2024-06-16 23:02 UTC by beviggiano

This PR introduces a complete implementation of the complaints entity and integrates a popup reporting feature for posts.

2024-06-16 23:53 UTC, edu-correia requested changes
3 points to give a look

2024-06-16 23:53 UTC, edu-correia commented on backend/src/infra/api/modules/complaints/controller.ts
> +class ComplaintsController {
Missing docs comments for this controller

2024-06-16 23:53 UTC, edu-correia commented on backend/src/infra/api/modules/complaints/routes.ts
> +router.put("/:id", verifyJWT, complaintsController.update); // Adicionado
We can remove this "// Adicionado" comment

2024-06-16 23:53 UTC, edu-correia commented on frontend/src/hooks/usePostComplaints.ts
> +      await axios.post('http://localhost:3333/complaints', {
Do not use the api like this, use like this:

```ts
import api from "<path>/src/api/api.ts";

await api.post('/complaints') ...
```
This way, we have one file that manages our **backend url** for the entire project

2024-06-18 02:32 UTC, edu-correia requested changes
one small change

2024-06-18 02:32 UTC, edu-correia commented on frontend/src/api/api.ts
There is already a file just like this in src/services/api.ts
Please delete this one and update the import on the other files
Sorry if my last comment was misleading on where the file was located.

2024-06-19 12:26 UTC, juancoelhoo approved these changes

2024-06-22 17:41 UTC, edu-correia approved these changes
LGTM

2024-06-22 17:45 UTC, merged