Feature/individual ad
juancoelhoo/pet-adoption pull request #20
Opened 2024-06-17 16:59 UTC by juancoelhoo

I implemented the advertisement pop-up and the dropdown menu.

2024-06-17 17:12 UTC, beviggiano commented on frontend/src/components/PedAd-Popup/PedAd-Popup.css
No comments on CSS files please

2024-06-17 17:12 UTC, beviggiano commented on frontend/src/pages/Advertisement/Advertisement.css
Here as well

2024-06-17 17:13 UTC, beviggiano requested changes
Just some points about CSS files

2024-06-17 18:23 UTC, beviggiano reviewed
It's all ok for me

2024-06-17 18:23 UTC, beviggiano approved these changes

2024-06-18 02:17 UTC, edu-correia requested changes
Just 2 points to change

2024-06-18 02:17 UTC, edu-correia commented on frontend/src/components/PetAd/PetAd.tsx
>            Raça: <span className="pet-info">Pastor alemão</span>
change "Pastor alemão" to {breed}

2024-06-18 02:17 UTC, edu-correia commented on frontend/src/components/PetAd/PetAd.tsx
>            <img src={descimage} alt="" />
change "Lorem, ipsum dolor sit amet" to {description} in the line below

2024-06-19 12:15 UTC, juancoelhoo commented on frontend/src/components/PetAd/PetAd.tsx
>            Raça: <span className="pet-info">Pastor alemão</span>
Thanks!

2024-06-19 16:00 UTC, beviggiano approved these changes

2024-06-22 17:42 UTC, edu-correia approved these changes
LGTM

2024-06-22 18:26 UTC, merged