Advertisement development
juancoelhoo/pet-adoption pull request #8
Opened 2024-06-03 21:09 UTC by juancoelhoo

Advertisement page created.

2024-06-04 12:48 UTC, beviggiano approved these changes
Great job, Juan! You did an amazing job! It's just like our prototype.

2024-06-05 02:27 UTC, edu-correia requested changes
Looking very good man, just 2 points to be aware

2024-06-05 02:27 UTC, edu-correia commented on frontend/src/App.tsx
> +                    <Route path="/" element={<AdvertisementScreen/>} />
with my latest change, we can already specify the path ( path="/feed" )

2024-06-05 02:27 UTC, edu-correia commented on frontend/src/components/Menu/Menu.css
> +@import url("https://fonts.googleapis.com/css2?family=Luckiest+Guy&family=Quicksand:wght@400;700&display=swap");
We will use this font in the whole project, so we can move this import to global.css so we won't need to add this in every css file

2024-06-05 02:31 UTC, edu-correia commented
Also, your change has some merge conflicts that you need to resolve before we can merge.
You will need to pull the latest version of the main branch and rebase with your changes, if you have any questions on how to do that, please let me know

2024-06-06 23:16 UTC, merged